ログインペイジ追加
Masashige-T/SOKUNE pull request #12
Opened 2020-10-30 03:58 UTC by codercfx

public/css/にlogin.css追加しました。

2020-10-30 04:17 UTC, Masashige-T requested changes
trelloにあるコーディング規約に合わせる形で修正をお願いします

2020-10-30 04:17 UTC, Masashige-T commented on public/css/login.css
> +    margin-top: 30px;
cssのプロパティはアルファベット順にしましょう

2020-10-30 04:17 UTC, Masashige-T commented on public/css/login.css
> +    background-color: #ffffff;
16進数、HEX形式の指定は可能なら3文字にしましょう

2020-10-30 04:17 UTC, Masashige-T commented on public/css/login.css
> +    font-size: 0.8rem;
小数点指定の時は0を省略しましょう

2020-10-30 04:17 UTC, Masashige-T commented on public/css/login.css
> +.remember-group {
ユーザーがクリックできるところなのでcursorの指定が欲しいです

2020-10-30 07:11 UTC, Etotomohiro requested changes
できればカンプ通りにお願いしたいのです。
もし変更したいとかあるなら事前に教えてください
１ページだけ違うと統一感が失われます

2020-10-30 07:15 UTC, codercfx commented
> できればカンプ通りにお愿いしたいのです。
> もし変更したいとかあるなら事前に教えてください
> 1ページだけ违うと统一感が失われます

了解です。

2020-10-31 15:04 UTC, ttrweb reviewed
細かい部分を修正すれば問題なさそう

2020-11-02 12:40 UTC, Masashige-T approved these changes
CSS問題なさそうです！
素晴らしい！！

2020-11-02 13:45 UTC, ttrweb approved these changes
ローカル環境で動作確認しました
コード良いと思います

2020-11-04 07:42 UTC, Etotomohiro approved these changes
OKです

2020-11-04 08:52 UTC, merged