indexページ追加
Masashige-T/SOKUNE pull request #15
Opened 2020-11-04 07:49 UTC by nngeinrei

cssはPC版のみ

2020-11-04 07:55 UTC, Masashige-T requested changes
trelloにあるコーディング規約に合う形でcssの修正をお願いします！
HTMLのclass命名に関しては問題なさそうです

2020-11-04 07:55 UTC, Masashige-T commented on public/css/app.css
> +}
cssの記述順をアルファベット順にしましょう

2020-11-04 07:55 UTC, Masashige-T commented on public/css/top.css
> +}
インデントを2で統一してください！

2020-11-04 08:08 UTC, nngeinrei commented on public/css/app.css
> +}
ごめんなさい

2020-11-04 08:08 UTC, nngeinrei commented on public/css/top.css
> +}
本当にそのとおり

2020-11-20 02:54 UTC, Masashige-T approved these changes
HTML CSS問題ありません💅

2020-11-29 08:50 UTC, Etotomohiro approved these changes

2020-12-01 08:23 UTC, merged