update: マイページへのリンクを画像に ナビゲーションの並びをデザインカンプ準拠へ
Masashige-T/SOKUNE pull request #8
Opened 2020-10-18 15:17 UTC by Masashige-T

軽微修正

XDデータに合わせる形で並びを変えました

マイページへのリンクが画像出てなかったため表示

2020-10-19 05:44 UTC, ttrweb commented
マージブロックされてる
いいですね

2020-10-20 01:40 UTC, Masashige-T commented
@Etotomohiro 
お手すきの際にレビュー頂けると幸いです

2020-10-20 01:42 UTC, Etotomohiro requested changes
好き

2020-10-20 01:43 UTC, Etotomohiro approved these changes

2020-10-20 03:04 UTC, merged